---
title: "Run_Analysis"
format: html
---

# Source everything :D

```{r}
source("./src/Source_Everything.R") # Load all functions
source("./LoadSamples.R") # Load samples and relations

# Install_Packages(packages) 
```


```{r}
Check_SampleName(samplesDF$SampleName)


dir <- "./data/input/processed/"

# Generate the Diann Report from the report.parquet
# HeLa + Yeast
diannReport <- Make_DiannReport(samplesDF, organism = "")
write.csv(diannReport, paste0(dir, "diannReport_HY.csv")

# Yeast
yeast_DiannReport <- dplyr::filter(diannReport, stringr::str_detect(Protein.Names, "YEAST"))
write.csv(diannReport, paste0(dir, "diannReport_YEAST.csv")

# HeLa
human_DiannReport <- dplyr::filter(diannReport, stringr::str_detect(Protein.Names, "HUMAN"))
write.csv(diannReport, paste0(dir, "diannReport_HeLa.csv")



# Generate the Diann Matrix from the Diann Report
# HeLa + Yeast
diannMatrix <- log2(Make_DiannMatrix(diannReport, header = "Genes") + 1)
write.csv(diannReport, paste0(dir, "diannMatrix_HY.csv")

# Yeast
yeast_DiannMatrix <- log2(Make_DiannMatrix(yeast_DiannReport, header = "Genes") + 1)
write.csv(diannReport, paste0(dir, "diannMatrix_YEAST.csv")

# HeLa
human_DiannMatrix <- log2(Make_DiannMatrix(human_DiannReport, header = "Genes") + 1)
write.csv(diannReport, paste0(dir, "diannMatrix_HeLa.csv")


```

# Precursor x RT
```{r}
chromatogram <- Plot_Chromatogram(diannReport, fancyLabels, colors, cols = 5) +
  ggplot2::labs(title = "HeLa + Yeast") +
  ggplot2::theme(plot.title = ggplot2::element_text(size = 12, face = "bold", vjust = 0.5, hjust = 0.5))


ggplot2::ggsave(
  filename = paste0("Chromatogram", ".png"),
  path = "./data/output/basic/",
  plot = chromatogram,
  width = 20, height = 10,
  units = "cm", dpi = 300
)

rm(chromatogram)
```

# Ion Cloud

```{r}
ionCloud <- Plot_IonCloud(diannReport, fancyLabels, cols = 5) +
  ggplot2::labs(title = "HeLa + Yeast") +
  ggplot2::theme(plot.title = ggplot2::element_text(size = 12, face = "bold", vjust = 0.5, hjust = 0.5))

ggplot2::ggsave(
  filename = paste0("ionCloud", ".png"),
  path = "./data/output/basic/",
  plot = ionCloud,
  width = 20, height = 10,
  units = "cm", dpi = 300
)

rm(ionCloud)
```


# Number of Peptides
```{r}
theme <- ggplot2::theme(
      plot.title = ggplot2::element_text(size = 12, face = "bold", vjust = 0.5),
      plot.subtitle = ggplot2::element_text(size = 8)
      )

# Count the peptides for:  Yeast and Human combined, Yeast only, and Human only
HY_nPeptides <- Plot_nPeptides(diannReport, fancyLabels, colors) +
    ggplot2::labs(title = "(A) HeLa + Yeast") + theme

Y_nPeptides <- Plot_nPeptides(yeast_DiannReport, fancyLabels, colors) +
    ggplot2::labs(title = "(B) Yeast") + theme

H_nPeptides <- Plot_nPeptides(human_DiannReport, fancyLabels, colors) +
    ggplot2::labs(title = "(C) HeLa") + theme

combine_Pept <- patchwork::wrap_plots(HY_nPeptides, Y_nPeptides, H_nPeptides, nrow = 1)

ggplot2::ggsave(
  filename = paste0("nPeptides", ".png"),
  path = "./data/output/basic/",
  plot = combine_Pept,
  width = 30, height = 12,
  units = "cm", dpi = 300)

rm(theme, HY_nPeptides, Y_nPeptides, H_nPeptides, combine_Pept)
```

# Number of Proteins
```{r}
theme <- ggplot2::theme(
      plot.title = ggplot2::element_text(size = 12, face = "bold", vjust = 0.5),
      plot.subtitle = ggplot2::element_text(size = 8)
      )

HY_nProteins <- Plot_nProteins(diannReport, labels = fancyLabels, colors) +
    ggplot2::labs(title = "(A) HeLa + Yeast") + theme

Y_nProteins <- Plot_nProteins(yeast_DiannReport, labels = fancyLabels, colors) +
    ggplot2::labs(title = "(B) Yeast") + theme

H_nProteins <- Plot_nProteins(human_DiannReport, labels = fancyLabels, colors) +
    ggplot2::labs(title = "(C) HeLa") + theme

combine_Prot <- patchwork::wrap_plots(HY_nProteins, Y_nProteins, H_nProteins)

ggplot2::ggsave(
  filename = paste0("nProteins", ".png"),
  path = "./data/output/basic/",
  plot = combine_Prot,
  width = 30, height = 12,
  units = "cm", dpi = 300)

rm(theme, HY_nProteins, Y_nProteins, H_nProteins, combine_Prot)
```

# Sparsity Matrix

```{r}
theme <- ggplot2::theme(
      plot.title = ggplot2::element_text(size = 25, face = "bold", vjust = 0.5)#,
      # plot.subtitle = ggplot2::element_text(size = 8)
      )

  HY_sparsity <- Plot_Sparsity(diannMatrix, fancyLabels) +
    ggplot2::labs(title = "(A) HeLa + Yeast") + theme

  Y_sparsity <- Plot_Sparsity(yeast_DiannMatrix, fancyLabels) +
    ggplot2::labs(title = "(B) Yeast") + theme

  H_sparsity <- Plot_Sparsity(human_DiannMatrix, fancyLabels) +
    ggplot2::labs(title = "(C) HeLa") + theme


combine_sparsity <- patchwork::wrap_plots(HY_sparsity, Y_sparsity, H_sparsity)

ggplot2::ggsave(
  filename = paste0("sparsity", ".png"),
  path = "./data/output/basic/",
  plot = combine_sparsity,
  width = 36, height = 26,
  units = "cm", dpi = 300
)

rm(HY_sparsity, Y_sparsity, H_sparsity, combine_sparsity, theme)
```