---
title: "Preliminary investigation of the carbamylation profile in proteins excreted in 24-hour urine after injection of Bothrops jararaca venom in a murine model"
author: "Pedro Galdiano de Castro"
execute:
  echo: false
  warning: false
  message: false
format: html
code-fold: true
editor_options:
  chunk_output_type: console
---

## ABSTRACT

Envenomation by *Bothrops jararaca* is considered a neglected disease by the World Health Organization that causes high morbidity and mortality. Among the main causes of mortality due to *Bothrops* envenomation is acute renal failure. Investigations of the proteome by mass spectrometry in plasma or renal tissue samples in murine models suggest potential candidates for markers of acute renal injury, such as the proteins NGAL and ITIH4. A less explored approach to search for markers of renal injury is the investigation of post translation modifications of proteins excreted in the urine of envenomed individuals. Elevated plasma urea levels are a striking feature among the changes commonly detected in blood samples from individuals who have been victims of snakebite. Uremia can be a sign of deterioration of renal function and can be associated with carbamylation of the amino terminus of proteins and the side chain of Lys residues. Carbamylation is a hallmark of aging that can be detected in the proteome, but it is underestimated as a hallmark of diseases that evolve with elevated urea. The present project aims to investigate the carbamylation profile of proteins excreted in 24-hour urine of animals injected with *B. jararaca* venom. The *in vivo* experiment with Swiss mice was conducted at the Laboratory of Applied Toxinology of Butantan Institute and the present project proposes the evaluation of urine samples from animals injected with 1.6 mg/kg of *B. jararaca* venom, pretreated with cathepsin or meprin inhibitors. The samples were reduced with 5 mM TCEP, alkylated with 20 mM chloroacetamide and digested with trypsin (1:100) using the SP3 protocol (Single-Pot, Solid-Phase-enhanced Sample Preparation). The samples were analyzed in the Vanquish Neo – Obritrap Exploris 480 system in data-independent acquisition (DIA) mode. Peptide identifications and protein inference were performed using the DIA-NN v2.1.0 search engine with the *Mus musculus* reference database containing only canonical sequences. Statistical analyses were performed using R version 4.2.2 with scripts developed specifically for the project.


Prepare something
```{r}
source("teste.R")

packages_activate() #Load all the dependencies


labels <- c(
  P1_02 = "Venom r1",
  P1_03 = "Venom r2",
  P1_04 = "Actinonin 30 mg r1",
  P1_05 = "Actinonin 30 mg r2",
  P1_07 = "Ven + Actn 30 mg r1",
  P1_08 = "Ven + Actn30 mg r2",
  P1_09 = "Ven + Actn_30 mg r3",
  P1_10 = "JPMOEt 100 mg r1",
  P1_11 = "JPMOEt 100 mg r2",
  P1_12 = "JPMOEt 100 mg r3",
  P1_13 = "Ven + jPMOEt 100 mg r1",
  P1_14 = "Ven + jPMOEt 100 mg r2",
  P1_15 = "Ven + jPMOEt 100 mg r3",
  P2_01 = "NaCl r1",
  P2_02 = "NaCl r2",
  P2_03 = "NaCl r3",
  P2_04 = "Actinonin 15 mg r1",
  P2_05 = "Actinonin 15 mg r2",
  P2_06 = "Actinonin 15 mg r3",
  P2_07 = "Ven + Actn 15 mg r1",
  P2_08 = "Ven + Actn 15 mg r2",
  P2_09 = "Ven + Actn 15 mg r3",
  P2_11 = "JPMOEt 50 mg r1",
  P2_12 = "JPMOEt 50 mg r2",
  P2_13 = "Ven + jPMOEt 50 mg r1",
  P2_14 = "Ven + jPMOEt 50 mg r2",
  P2_15 = "Ven + jPMOEt 50 mg r3"
)
                
levels <- c(
  "NaCl_r1", "NaCl_r2", "NaCl_r3",
  "Actinonin_15mg_r1", "Actinonin_15mg_r2", "Actinonin_15mg_r3",
  "Actinonin_30mg_r1", "Actinonin_30mg_r2", 
  "JPMOEt_50mg_r1", "JPMOEt_50mg_r2",
  "JPMOEt_100mg_r1", "JPMOEt_100mg_r2", "JPMOEt_100mg_r3",
  "Venom_r1", "Venom_r2",
  "Ven_Actn_15mg_r1", "Ven_Actn_15mg_r2", "Ven_Actn_15mg_r3",
  "Ven_Actn_30mg_r1", "Ven_Actn_30mg_r2", "Ven_Actn_30mg_r3",
  "Ven_jPMOEt_50mg_r1", "Ven_jPMOEt_50mg_r2", "Ven_jPMOEt_50mg_r3",
  "Ven_jPMOEt_100mg_r1", "Ven_jPMOEt_100mg_r2", "Ven_jPMOEt_100mg_r3")





```




